# PoseKit Web Application Dockerfile
FROM node:18-alpine

# Install system dependencies
RUN apk add --no-cache libc6-compat curl

# Set working directory
WORKDIR /app

# Copy web application files
COPY apps/web ./

# Remove workspace dependency to avoid build issues
RUN sed -i 's/"@posekit\/types": "file:.*"/"@posekit\/types": "^1.0.0"/g' package.json || true

# Install dependencies
RUN npm install --legacy-peer-deps

# Build arguments
ARG NEXT_PUBLIC_API_URL=https://api.posekit.com
ARG NEXT_PUBLIC_CDN_URL=https://cdn.posekit.com

# Set environment variables
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_CDN_URL=$NEXT_PUBLIC_CDN_URL
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Build the application
RUN npm run build

# Add non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Set ownership
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD curl -f http://localhost:3000/ || exit 1

CMD ["npm", "start"]