# PoseKit Web Application Dockerfile
FROM node:18-alpine

# Install system dependencies
RUN apk add --no-cache libc6-compat curl

# Set working directory
WORKDIR /app

# Copy web application files
COPY apps/web ./

# Remove workspace dependency completely
RUN sed -i '/"@posekit\/types":/d' package.json

# Add missing dependencies that were removed
RUN sed -i '/"framer-motion"/a\    "react-dropzone": "^14.2.3",' package.json

# Install dependencies
RUN npm install --legacy-peer-deps

# Replace @posekit/types imports with local types
RUN find . -name "*.ts" -o -name "*.tsx" | xargs sed -i "s|from '@posekit/types'|from '@/types'|g"
RUN find . -name "*.ts" -o -name "*.tsx" | xargs sed -i "s|import.*@posekit/types.*|// Removed @posekit/types import|g"

# Build arguments
ARG NEXT_PUBLIC_API_URL=https://api.posekit.com
ARG NEXT_PUBLIC_CDN_URL=https://cdn.posekit.com

# Set environment variables
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_CDN_URL=$NEXT_PUBLIC_CDN_URL
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Build the application
RUN npm run build

# Add non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Set ownership
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD curl -f http://localhost:3000/ || exit 1

CMD ["npm", "start"]